In [51]:
import pandas as pd
import numpy as np
from math import radians, cos, sin, asin, sqrt

df = pd.read_csv('202001/20200101/20200101-00.csv')

def haversine(lon1, lat1, lon2, lat2):
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a))
    km = 6371* c
    m = km * 1000
    return m

In [52]:
df['lat1'] = df['lat'].shift(-1)
df['lon1'] = df['lon'].shift(-1)

df

,Unnamed: 0,VehicleID,gpsvalid,lat,lon,timestamp,speed,heading,for_hire_light,engine_acc,lat-lon,BKK,clusterID,pickup,dropoff,lat1,lon1
0,3849,++iY830QzVXT6Slkr+8ftkTzMN4,1,13.77085,100.47392,2020-01-01 00:01:28,0,333,0,0,13.7708-100.4739,True,NaN,False,False,13.77085,100.47392
1,10766,++iY830QzVXT6Slkr+8ftkTzMN4,1,13.77085,100.47392,2020-01-01 00:04:28,0,333,0,0,13.7708-100.4739,True,NaN,False,False,13.77085,100.47392
2,17731,++iY830QzVXT6Slkr+8ftkTzMN4,1,13.77085,100.47392,2020-01-01 00:07:28,0,333,0,0,13.7708-100.4739,True,NaN,False,False,13.77085,100.47392
3,23939,++iY830QzVXT6Slkr+8ftkTzMN4,1,13.77085,100.47392,2020-01-01 00:10:28,0,333,0,0,13.7708-100.4739,True,NaN,False,False,13.77085,100.47392
4,31950,++iY830QzVXT6Slkr+8ftkTzMN4,1,13.77085,100.47392,2020-01-01 00:13:28,0,333,0,0,13.7708-100.4739,True,NaN,False,False,13.77085,100.47392
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147434,113749,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.59584,100.31354,2020-01-01 00:45:36,0,359,1,0,13.5958-100.3135,False,NaN,False,False,13.59584,100.31354
147435,120526,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.59584,100.31354,2020-01-01 00:48:35,0,359,1,0,13.5958-100.3135,False,NaN,False,False,13.59584,100.31354
147436,127326,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.59584,100.31354,2020-01-01 00:51:36,0,359,1,0,13.5958-100.3135,False,NaN,False,False,13.59584,100.31354
147437,134053,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.59584,100.31354,2020-01-01 00:54:35,0,359,1,0,13.5958-100.3135,False,NaN,False,False,13.59584,100.31354
147438,140792,zzLYPcDONaA8lLF2aJYFKnoRDQ4,1,13.59584,100.31354,2020-01-01 00:57:35,0,359,1,0,13.5958-100.3135,False,NaN,False,False,NaN,NaN

In [54]:
df['distance'] = df.apply(lambda x: haversine(x.lon, x.lat, x.lon1, x.lat1), axis=1)

In [59]:
df['distance'].unique().size

64380